# Generated by Django 3.2.20 on 2023-11-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_events', '0027_auto_20211221_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlistplugin',
            name='style',
            field=models.CharField(choices=[('standard', 'Stacked'), ('horizontal', 'Horizontal')], default='standard', max_length=50, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='upcomingpluginitem',
            name='style',
            field=models.CharField(choices=[('standard', 'Stacked'), ('horizontal', 'Horizontal')], default='standard', max_length=50, verbose_name='Style'),
        ),
    ]
